name: Tests
'on':
  push:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run start -- test.node.reporters

      - name: Test Report
        uses: dorny/test-reporter@dev
        if: success() || failure()
        with:
          name: Tests
          path: test-results-json
          reporter: mocha-json
